export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
//
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";
export const SHOW_PROFILE = "SHOW_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
//
export const CREATE_QUESTION_ANSWERS = "CREATE_QUESTION_ANSWERS";
export const UPDATE_QUESTION_ANSWERS = "UPDATE_QUESTION_ANSWERS";
export const UPDATE_TIME = "UPDATE_TIME";

export const SHOW_QUESTION_ANSWERS = "SHOW_QUESTION_ANSWERS";
export const SHOW_QUESTION_AFTER_DELETE = "SHOW_QUESTION_AFTER_DELETE";
export const SHOW_SUBJECT = "SHOW_SUBJECT";
export const GET_QUESTION_TABLE_BY_SUBJECT = "GET_QUESTION_TABLE_BY_SUBJECT";
export const SHOW_QUESTION_TABLE_BY_SUBJECT = "SHOW_QUESTION_TABLE_BY_SUBJECT";

export const CREATE_QUESTION_TABLE = "CREATE_QUESTION_TABLE";
export const UPDATE_QUESTION_TABLE_QUESTION = "UPDATE_QUESTION_TABLE_QUESTION";
export const UPDATE_QUESTION_TABLE = "UPDATE_QUESTION_TABLE";

export const SHOW_ANSWER_RECORD = "SHOW_ANSWER_RECORD";

//USER
export const SHOW_QUESTION_TABLE = "SHOW_QUESTION_TABLE";
export const SHOW_QUESTION_TABLE_COMPLETED = "SHOW_QUESTION_TABLE_COMPLETED";
export const GET_QUESTION_TABLE_COMPLETED = "GET_QUESTION_TABLE_COMPLETED";
export const UPDATE_USER = "UPDATE_USER";
export const CLOSE_CODE_QUESTION_TABLE = "CLOSE_CODE_QUESTION_TABLE";
export const SHOW_ONE_QUESTION_TABLE = "SHOW_ONE_QUESTION_TABLE";
export const SHOW_USER_ATTEMPT = "SHOW_USER_ATTEMPT";
export const CHECK_USER_DO_QUIZ = "CHECK_USER_DO_QUIZ";
